# Generated by Django 4.2.5 on 2023-11-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='color',
        ),
        migrations.AddField(
            model_name='clothes',
            name='color',
            field=models.ManyToManyField(to='core.colors'),
        ),
    ]
