# Generated by Django 4.2.5 on 2023-11-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_cartproduct_options_cartproduct_overall_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
