# Generated by Django 4.2.5 on 2023-11-20 13:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_blog_blogcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='category_and_tags',
            field=models.ManyToManyField(to='core.blogcategories'),
        ),
        migrations.AddField(
            model_name='blog',
            name='comment_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
