# Generated by Django 4.2.5 on 2023-11-20 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_blog_author_blog_category_and_tags_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Blogs', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterModelOptions(
            name='blogcategories',
            options={'verbose_name': 'Blog categories', 'verbose_name_plural': 'Blog categories'},
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='category_az',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='category_en',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='color_az',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='color_en',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='materials_az',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='materials_en',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='tag_az',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='tag_en',
        ),
    ]
