# Generated by Django 4.2.5 on 2023-11-20 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_clothes_description_az_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='name_az',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='name_en',
        ),
    ]
