# Generated by Django 4.2.5 on 2023-11-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_clothes_name_az_remove_clothes_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='name_az',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clothes',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
