# Generated by Django 4.2.5 on 2023-11-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_clothes_name_az_clothes_name_en'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='category_and_tags',
            new_name='categories',
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(to='core.tags'),
        ),
    ]
