# Generated by Django 4.2.5 on 2023-11-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_rename_category_and_tags_blog_categories_blog_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='colors',
            name='color_az',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='colors',
            name='color_en',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
