# Generated by Django 4.2.5 on 2023-11-30 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_colors_color_az_colors_color_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='tag_az',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tags',
            name='tag_en',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
