# Generated by Django 4.2.5 on 2023-11-30 06:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_categories_category_az_categories_category_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='description_az',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='clothes',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='clothes',
            name='materials_az',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='clothes',
            name='materials_en',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
