# Generated by Django 4.2.5 on 2023-11-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_blog_description_az_blog_description_en_blog_name_az_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='adress_az',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='adress_en',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='info_az',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='info_en',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
