# Generated by Django 4.2.5 on 2023-11-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_settings_adress_az_settings_adress_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='size',
            field=models.ManyToManyField(null=True, to='core.sizes'),
        ),
    ]
