# Generated by Django 4.2.5 on 2023-11-30 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_categories_category_az_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcategories',
            name='category_az',
        ),
        migrations.RemoveField(
            model_name='blogcategories',
            name='category_en',
        ),
    ]
