# Generated by Django 4.2.7 on 2023-12-07 11:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='our_mission_text_az',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='our_mission_text_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='our_story_text_az',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='our_story_text_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
