# Generated by Django 4.2.7 on 2023-12-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_about_our_mission_text_az_about_our_mission_text_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/product_images/'),
        ),
    ]
