# Generated by Django 4.2.7 on 2023-12-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_about_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='colors',
            name='color_az',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='colors',
            name='color_en',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
