# Generated by Django 4.2.7 on 2023-12-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_colors_color_az_colors_color_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizes',
            name='size_az',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sizes',
            name='size_en',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
