# Generated by Django 4.2.7 on 2023-12-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_sizes_size_az_sizes_size_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='category_az',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='category_en',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
