# Generated by Django 4.2.7 on 2023-12-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_categories_category_az_categories_category_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='tag_az',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tags',
            name='tag_en',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
