# Generated by Django 4.2.7 on 2023-12-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_blogcategories_category_az_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='color_az',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='color_en',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='size_az',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='size_en',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
