# Generated by Django 4.2.7 on 2023-12-11 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_cartproduct_product_az_cartproduct_product_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='product_az',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='product_en',
        ),
    ]
