# Generated by Django 4.2.7 on 2023-12-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_cozastoregallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='google_plus',
            field=models.URLField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='twitter',
            field=models.URLField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='facebook',
            field=models.URLField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='instagram',
            field=models.URLField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='pinterest',
            field=models.URLField(max_length=50, null=True),
        ),
    ]
