# Generated by Django 4.2.7 on 2023-12-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_settings_google_plus_settings_twitter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
