# Generated by Django 4.2.7 on 2023-12-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_blogcomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomments',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='blogcomments',
            name='message',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='blogcomments',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
